### ISSUE TITLE
Quickupload dropzone styling and position

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.tabbedview#38]
There are some points to improve the dropzone:
Currently the dropzone is hidden and only visible if a file is dragged over. The user may miss the feature since he never sees the dropzone.

(All screenshots from GEVER instance)
This is a screenshot where the dropzone is visible by default.
The dropzone takes, even when made smaller, a lot of space and might distract from the actual content.
This is why we could add a close button to hide the dropzone (which restores the original behavior).
![screen shot 2014-07-28 at 11 37 00](https://cloud.githubusercontent.com/assets/1375745/3718794/ccb287b8-163a-11e4-8fd7-3e331dae6a4a.png)
During download (failed download for screenshot):
![screen shot 2014-07-28 at 11 44 52](https://cloud.githubusercontent.com/assets/1375745/3718875/fc1492c0-163b-11e4-9792-8099f928bae1.png)

The dropzone is also a functionality of the folder, not the tab. The dropzone appears currently in all tabs. This is good because switching tabs to upload something is way too complicated. But it can be confusing. Eg. you can upload files in the journal tab or in GEVER in the trashbin-tab.
To solve this problem we propose to move the dropzone above the tabbedview:
![screen shot 2014-07-28 at 11 47 44](https://cloud.githubusercontent.com/assets/1375745/3718930/de29cebe-163c-11e4-8480-45ebb1f59de9.png)

Since the dropzone can be hidden we should give the user a possibility to unhide it:
![screen shot 2014-07-28 at 12 01 37](https://cloud.githubusercontent.com/assets/1375745/3719027/3c86b552-163e-11e4-9b90-17d25be87a40.png)

/cc @maethu @phgross

**Comment by bierik** [comment]
Wurde durch https://github.com/4teamwork/ftw.tabbedview/pull/54 gelöst.
